import react from './assets/skillLogo/react.svg'
import nextjs from './assets/skillLogo/nextjs.svg'
import angular from './assets/skillLogo/angular.svg'
import aws from './assets/skillLogo/aws.svg'
import bootstrap from './assets/skillLogo/bootstrap.svg'
import cloudflare from './assets/skillLogo/cloudflare.svg'
import cloudfront from './assets/skillLogo/cloudfront.svg'
import css3 from './assets/skillLogo/css3.svg'
import docker from './assets/skillLogo/docker.svg'
import expressjs from './assets/skillLogo/expressjs.png'
import git from './assets/skillLogo/git.svg'
import github from './assets/skillLogo/github.png'
import html5 from './assets/skillLogo/html5.svg'
import jasmine from './assets/skillLogo/jasmine.svg'
import java from './assets/skillLogo/java.svg'
import javascript from './assets/skillLogo/javascript.svg'
import jira from './assets/skillLogo/jira.svg'
import kafka from './assets/skillLogo/kafka.png'
import karma from './assets/skillLogo/karma.svg'
import mongodb from './assets/skillLogo/mongodb.svg'
import mysql from './assets/skillLogo/mysql.svg'
import nodejs from './assets/skillLogo/nodejs.svg'
import oauth from './assets/skillLogo/oauth.svg'
import postgresql from './assets/skillLogo/postgresql.svg'
import prisma from './assets/skillLogo/prisma.svg'
import recoil from './assets/skillLogo/recoil.svg'
import redis from './assets/skillLogo/redis.svg'
import tailwindcss from './assets/skillLogo/tailwindcss.svg'
import typescript from './assets/skillLogo/typescript.svg'
import vercel from './assets/skillLogo/vercel.png'
import websocket from './assets/skillLogo/websocket.svg'

export const SKILLS_LIST = [
    {name: 'React.js', icon: react},
    {name: 'Next.js', icon: nextjs},
    {name: 'Recoil.js', icon: recoil},
    {name: 'Angular.js', icon: angular},
    {name: 'Typescript', icon: typescript},
    {name: 'TailwindCSS', icon: tailwindcss},
    {name: 'Bootstrap', icon: bootstrap},
    {name: 'Javascript', icon: javascript},
    {name: 'HTML5', icon: html5},
    {name: 'CSS3', icon: css3},
    {name: 'Java', icon: java},
    {name: 'OAuth 2.0', icon: oauth},
    {name: 'Node.js', icon: nodejs},
    {name: 'Express.js', icon: expressjs},
    {name: 'Redis', icon: redis},
    {name: 'WebSockets', icon: websocket},
    {name: 'Kafka', icon: kafka},
    {name: 'MySql', icon: mysql},
    {name: 'MongoDb', icon: mongodb},
    {name: 'PostgreSQL', icon: postgresql},
    {name: 'Prisma', icon: prisma},
    {name: 'AWS', icon: aws},
    {name: 'Cloudflare', icon: cloudflare},
    {name: 'Amazon CloudFront', icon: cloudfront},
    {name: 'Docker', icon: docker},
    {name: 'Vercel', icon: vercel},
    {name: 'Git', icon: git},
    {name: 'GitHub', icon: github},
    {name: 'Jira', icon: jira},
    {name: 'Karma', icon: karma},
    {name: 'Jasmine', icon: jasmine}
] 